// Advanced Dashboard & Analytics Data Module
const DASHBOARD_DATA = {
  analytics: {
    title: "Analytics Dashboard",
    description: "Track your learning progress with detailed analytics and insights",
    color: "var(--info)",
    subtopics: {
      "Learning Analytics": [
        {
          id: "progress-overview",
          title: "Learning Progress Overview",
          tags: ["analytics", "dashboard", "progress"],
          summary: "Visualize your learning journey with interactive charts and statistics.",
          content: `
<div class="analytics-dashboard">
  <div class="analytics-header">
    <h3>📊 Learning Analytics</h3>
    <p>Track your progress and identify areas for improvement</p>
  </div>
  
  <div class="stats-overview">
    <div class="stat-card">
      <div class="stat-icon">📚</div>
      <div class="stat-value" id="topics-completed">0</div>
      <div class="stat-label">Topics Completed</div>
      <div class="stat-change positive">+12 this week</div>
    </div>
    <div class="stat-card">
      <div class="stat-icon">⏱️</div>
      <div class="stat-value" id="study-hours">0</div>
      <div class="stat-label">Study Hours</div>
      <div class="stat-change positive">+8.5 this week</div>
    </div>
    <div class="stat-card">
      <div class="stat-icon">📝</div>
      <div class="stat-value" id="quiz-score">0%</div>
      <div class="stat-label">Avg Quiz Score</div>
      <div class="stat-change positive">+5% improvement</div>
    </div>
    <div class="stat-card">
      <div class="stat-icon">🔥</div>
      <div class="stat-value" id="current-streak">0</div>
      <div class="stat-label">Day Streak</div>
      <div class="stat-change">Personal best: 45</div>
    </div>
  </div>
  
  <div class="charts-grid">
    <div class="chart-container wide">
      <h4>Weekly Study Activity</h4>
      <div class="activity-chart" id="weekly-activity">
        <!-- Generated by JS -->
      </div>
    </div>
    
    <div class="chart-container">
      <h4>Skills Distribution</h4>
      <div class="skills-radar" id="skills-chart">
        <svg viewBox="0 0 200 200" class="radar-svg">
          <!-- Background polygons -->
          <polygon points="100,20 170,70 170,130 100,180 30,130 30,70" fill="none" stroke="var(--border)" stroke-width="1"/>
          <polygon points="100,40 150,75 150,125 100,160 50,125 50,75" fill="none" stroke="var(--border)" stroke-width="1"/>
          <polygon points="100,60 130,80 130,120 100,140 70,120 70,80" fill="none" stroke="var(--border)" stroke-width="1"/>
          
          <!-- Data polygon -->
          <polygon id="radar-data" points="100,30 160,75 150,130 100,170 40,125 35,70" 
                   fill="rgba(99, 102, 241, 0.3)" stroke="var(--accent)" stroke-width="2"/>
          
          <!-- Labels -->
          <text x="100" y="15" text-anchor="middle" fill="var(--text-secondary)" font-size="10">Cloud</text>
          <text x="185" y="70" text-anchor="start" fill="var(--text-secondary)" font-size="10">K8s</text>
          <text x="185" y="135" text-anchor="start" fill="var(--text-secondary)" font-size="10">DevOps</text>
          <text x="100" y="195" text-anchor="middle" fill="var(--text-secondary)" font-size="10">Linux</text>
          <text x="15" y="135" text-anchor="end" fill="var(--text-secondary)" font-size="10">Security</text>
          <text x="15" y="70" text-anchor="end" fill="var(--text-secondary)" font-size="10">Network</text>
        </svg>
      </div>
    </div>
    
    <div class="chart-container">
      <h4>Category Progress</h4>
      <div class="category-bars" id="category-progress">
        <div class="progress-row">
          <span class="cat-name">Networking</span>
          <div class="progress-bar-container">
            <div class="progress-fill" style="width: 75%"></div>
          </div>
          <span class="cat-percent">75%</span>
        </div>
        <div class="progress-row">
          <span class="cat-name">Cloud</span>
          <div class="progress-bar-container">
            <div class="progress-fill" style="width: 60%"></div>
          </div>
          <span class="cat-percent">60%</span>
        </div>
        <div class="progress-row">
          <span class="cat-name">Kubernetes</span>
          <div class="progress-bar-container">
            <div class="progress-fill" style="width: 45%"></div>
          </div>
          <span class="cat-percent">45%</span>
        </div>
        <div class="progress-row">
          <span class="cat-name">DevOps</span>
          <div class="progress-bar-container">
            <div class="progress-fill" style="width: 55%"></div>
          </div>
          <span class="cat-percent">55%</span>
        </div>
        <div class="progress-row">
          <span class="cat-name">Linux</span>
          <div class="progress-bar-container">
            <div class="progress-fill" style="width: 80%"></div>
          </div>
          <span class="cat-percent">80%</span>
        </div>
      </div>
    </div>
  </div>
  
  <div class="learning-insights">
    <h4>💡 Insights & Recommendations</h4>
    <div class="insights-list">
      <div class="insight-card">
        <span class="insight-icon">🎯</span>
        <div class="insight-content">
          <h5>Focus Area Identified</h5>
          <p>Your Kubernetes knowledge is 30% below your average. Consider focusing on container orchestration this week.</p>
        </div>
      </div>
      <div class="insight-card">
        <span class="insight-icon">📈</span>
        <div class="insight-content">
          <h5>Great Progress!</h5>
          <p>You've completed 12 topics this week - that's 50% more than last week!</p>
        </div>
      </div>
      <div class="insight-card">
        <span class="insight-icon">⏰</span>
        <div class="insight-content">
          <h5>Optimal Study Time</h5>
          <p>You perform best on quizzes taken between 8-10 AM. Try scheduling study sessions during this time.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
// Generate weekly activity chart
const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const activityData = [2.5, 3.2, 1.8, 4.0, 2.2, 5.5, 3.8];
const maxActivity = Math.max(...activityData);

let activityHtml = '<div class="activity-bars">';
days.forEach((day, i) => {
  const height = (activityData[i] / maxActivity) * 100;
  activityHtml += \`
    <div class="activity-bar-wrapper">
      <div class="activity-bar" style="height: \${height}%" data-value="\${activityData[i]}"></div>
      <span class="activity-day">\${day}</span>
    </div>
  \`;
});
activityHtml += '</div>';
document.getElementById('weekly-activity').innerHTML = activityHtml;

// Load real stats from localStorage
const completed = JSON.parse(localStorage.getItem('infrahub_learned') || '[]');
document.getElementById('topics-completed').textContent = completed.length;

const xp = parseInt(localStorage.getItem('infrahub_xp') || '0');
document.getElementById('study-hours').textContent = Math.round(xp / 60 * 10) / 10;
<\/script>

<style>
.analytics-dashboard { max-width: 1200px; }
.analytics-header { margin-bottom: 32px; }
.analytics-header h3 { margin-bottom: 8px; }
.analytics-header p { color: var(--text-secondary); }

.stats-overview {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 20px;
  margin-bottom: 32px;
}
.stat-card {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 24px;
  text-align: center;
  transition: transform 0.2s;
}
.stat-card:hover {
  transform: translateY(-4px);
  border-color: var(--accent);
}
.stat-icon {
  font-size: 32px;
  margin-bottom: 12px;
}
.stat-value {
  font-size: 36px;
  font-weight: 700;
  color: var(--text-primary);
  line-height: 1;
}
.stat-label {
  font-size: 13px;
  color: var(--text-secondary);
  margin-top: 8px;
}
.stat-change {
  font-size: 12px;
  color: var(--text-tertiary);
  margin-top: 4px;
}
.stat-change.positive {
  color: var(--success);
}

.charts-grid {
  display: grid;
  grid-template-columns: 2fr 1fr 1fr;
  gap: 20px;
  margin-bottom: 32px;
}
.chart-container {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 20px;
}
.chart-container.wide {
  grid-row: span 1;
}
.chart-container h4 {
  font-size: 14px;
  color: var(--text-secondary);
  margin-bottom: 16px;
}

.activity-chart {
  height: 200px;
  display: flex;
  align-items: flex-end;
}
.activity-bars {
  display: flex;
  justify-content: space-around;
  align-items: flex-end;
  width: 100%;
  height: 100%;
  gap: 12px;
}
.activity-bar-wrapper {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  height: 100%;
}
.activity-bar {
  width: 100%;
  background: linear-gradient(to top, var(--accent), #818cf8);
  border-radius: 4px 4px 0 0;
  min-height: 4px;
  transition: height 0.5s ease;
  position: relative;
}
.activity-bar:hover::after {
  content: attr(data-value) ' hrs';
  position: absolute;
  top: -24px;
  left: 50%;
  transform: translateX(-50%);
  background: var(--accent);
  color: white;
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 11px;
  white-space: nowrap;
}
.activity-day {
  font-size: 12px;
  color: var(--text-tertiary);
}

.radar-svg {
  width: 100%;
  max-width: 250px;
  margin: 0 auto;
  display: block;
}

.category-bars { display: grid; gap: 12px; }
.progress-row {
  display: grid;
  grid-template-columns: 90px 1fr 40px;
  align-items: center;
  gap: 12px;
}
.cat-name {
  font-size: 12px;
  color: var(--text-secondary);
}
.progress-bar-container {
  height: 8px;
  background: var(--bg-tertiary);
  border-radius: 4px;
  overflow: hidden;
}
.progress-fill {
  height: 100%;
  background: linear-gradient(90deg, var(--accent), var(--success));
  border-radius: 4px;
  transition: width 0.5s ease;
}
.cat-percent {
  font-size: 12px;
  color: var(--text-tertiary);
  text-align: right;
}

.learning-insights h4 { margin-bottom: 16px; }
.insights-list { display: grid; gap: 12px; }
.insight-card {
  display: flex;
  gap: 16px;
  padding: 16px 20px;
  background: var(--bg-secondary);
  border-radius: var(--radius-md);
  border-left: 3px solid var(--accent);
}
.insight-icon {
  font-size: 24px;
}
.insight-content h5 {
  font-size: 14px;
  margin-bottom: 4px;
  color: var(--text-primary);
}
.insight-content p {
  font-size: 13px;
  color: var(--text-secondary);
  line-height: 1.5;
}

@media (max-width: 1024px) {
  .stats-overview { grid-template-columns: repeat(2, 1fr); }
  .charts-grid { grid-template-columns: 1fr; }
}
@media (max-width: 768px) {
  .stats-overview { grid-template-columns: 1fr; }
  .progress-row { grid-template-columns: 70px 1fr 35px; }
}
</style>`
        },
        {
          id: "study-planner",
          title: "Study Planner & Goals",
          tags: ["planner", "goals", "productivity"],
          summary: "Set learning goals, create study schedules, and track your commitments.",
          content: `
<div class="study-planner">
  <div class="planner-header">
    <h3>📅 Study Planner</h3>
    <p>Plan your learning journey and achieve your goals</p>
  </div>
  
  <div class="planner-grid">
    <div class="goals-section">
      <h4>🎯 Learning Goals</h4>
      <div class="goals-list" id="goals-list">
        <div class="goal-item" data-goal-id="1">
          <input type="checkbox" class="goal-check" checked>
          <div class="goal-content">
            <span class="goal-text completed">Complete AWS Cloud Practitioner</span>
            <span class="goal-deadline">Due: Mar 15, 2025</span>
          </div>
          <button class="goal-delete">×</button>
        </div>
        <div class="goal-item" data-goal-id="2">
          <input type="checkbox" class="goal-check">
          <div class="goal-content">
            <span class="goal-text">Pass CKA Certification</span>
            <span class="goal-deadline">Due: May 30, 2025</span>
          </div>
          <button class="goal-delete">×</button>
        </div>
        <div class="goal-item" data-goal-id="3">
          <input type="checkbox" class="goal-check">
          <div class="goal-content">
            <span class="goal-text">Complete 5 Hands-on Labs</span>
            <span class="goal-deadline">Due: Apr 30, 2025</span>
          </div>
          <button class="goal-delete">×</button>
        </div>
      </div>
      
      <div class="add-goal">
        <input type="text" id="new-goal-input" placeholder="Add a new learning goal...">
        <input type="date" id="new-goal-date">
        <button class="btn btn-primary" onclick="addGoal()">Add Goal</button>
      </div>
      
      <div class="goal-stats">
        <div class="stat-item">
          <span class="stat-number" id="completed-goals">1</span>
          <span class="stat-text">Completed</span>
        </div>
        <div class="stat-item">
          <span class="stat-number" id="pending-goals">2</span>
          <span class="stat-text">Pending</span>
        </div>
        <div class="stat-item">
          <span class="stat-number" id="completion-rate">33%</span>
          <span class="stat-text">Completion</span>
        </div>
      </div>
    </div>
    
    <div class="schedule-section">
      <h4>📆 Weekly Schedule</h4>
      <div class="schedule-calendar">
        <div class="day-schedule">
          <div class="day-header">
            <span class="day-name">Monday</span>
            <span class="day-date">Mar 9</span>
          </div>
          <div class="study-slots">
            <div class="study-slot completed">
              <span class="slot-time">08:00 - 09:30</span>
              <span class="slot-topic">AWS VPC Deep Dive</span>
            </div>
            <div class="study-slot">
              <span class="slot-time">19:00 - 20:30</span>
              <span class="slot-topic">Kubernetes Networking</span>
            </div>
          </div>
        </div>
        
        <div class="day-schedule">
          <div class="day-header">
            <span class="day-name">Tuesday</span>
            <span class="day-date">Mar 10</span>
          </div>
          <div class="study-slots">
            <div class="study-slot">
              <span class="slot-time">07:00 - 08:30</span>
              <span class="slot-topic">Terraform Modules</span>
            </div>
          </div>
        </div>
        
        <div class="day-schedule">
          <div class="day-header">
            <span class="day-name">Wednesday</span>
            <span class="day-date">Mar 11</span>
          </div>
          <div class="study-slots">
            <div class="study-slot">
              <span class="slot-time">19:00 - 21:00</span>
              <span class="slot-topic">Practice Quiz</span>
            </div>
          </div>
        </div>
      </div>
      
      <button class="btn btn-secondary" onclick="addStudySlot()">+ Add Study Session</button>
    </div>
  </div>
  
  <div class="focus-timer-section">
    <h4>🍅 Focus Timer</h4>
    <div class="timer-display">
      <div class="timer-circle">
        <svg viewBox="0 0 100 100">
          <circle cx="50" cy="50" r="45" fill="none" stroke="var(--border)" stroke-width="8"/>
          <circle id="timer-progress" cx="50" cy="50" r="45" fill="none" stroke="var(--accent)" stroke-width="8" 
                  stroke-dasharray="283" stroke-dashoffset="0" stroke-linecap="round"/>
        </svg>
        <div class="timer-text">
          <span id="timer-countdown">25:00</span>
          <span class="timer-label">Focus Time</span>
        </div>
      </div>
      <div class="timer-controls">
        <button class="timer-btn" onclick="startTimer()">▶ Start</button>
        <button class="timer-btn secondary" onclick="pauseTimer()">⏸ Pause</button>
        <button class="timer-btn secondary" onclick="resetTimer()">↺ Reset</button>
      </div>
    </div>
    <div class="timer-presets">
      <button class="preset-btn active" data-time="25">Pomodoro (25m)</button>
      <button class="preset-btn" data-time="45">Deep Work (45m)</button>
      <button class="preset-btn" data-time="15">Short Break (15m)</button>
    </div>
  </div>
</div>

<script>
let timerInterval;
let timeLeft = 25 * 60;
let totalTime = 25 * 60;
let isRunning = false;

function startTimer() {
  if (isRunning) return;
  isRunning = true;
  timerInterval = setInterval(() => {
    timeLeft--;
    updateTimerDisplay();
    if (timeLeft <= 0) {
      clearInterval(timerInterval);
      isRunning = false;
      alert('Focus session complete! Take a break.');
    }
  }, 1000);
}

function pauseTimer() {
  clearInterval(timerInterval);
  isRunning = false;
}

function resetTimer() {
  clearInterval(timerInterval);
  isRunning = false;
  timeLeft = totalTime;
  updateTimerDisplay();
}

function updateTimerDisplay() {
  const minutes = Math.floor(timeLeft / 60);
  const seconds = timeLeft % 60;
  document.getElementById('timer-countdown').textContent = 
    \`\${minutes.toString().padStart(2, '0')}:\${seconds.toString().padStart(2, '0')}\`;
  
  const progress = (timeLeft / totalTime) * 283;
  document.getElementById('timer-progress').style.strokeDashoffset = 283 - progress;
}

document.querySelectorAll('.preset-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.preset-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    totalTime = parseInt(btn.dataset.time) * 60;
    resetTimer();
  });
});

function addGoal() {
  const input = document.getElementById('new-goal-input');
  const dateInput = document.getElementById('new-goal-date');
  if (!input.value.trim()) return;
  
  const goalsList = document.getElementById('goals-list');
  const goalId = Date.now();
  const goalHtml = \`
    <div class="goal-item" data-goal-id="\${goalId}">
      <input type="checkbox" class="goal-check">
      <div class="goal-content">
        <span class="goal-text">\${input.value}</span>
        <span class="goal-deadline">Due: \${dateInput.value || 'No deadline'}</span>
      </div>
      <button class="goal-delete" onclick="deleteGoal(\${goalId})">×</button>
    </div>
  \`;
  goalsList.insertAdjacentHTML('beforeend', goalHtml);
  input.value = '';
  dateInput.value = '';
  updateGoalStats();
}

function deleteGoal(id) {
  const goal = document.querySelector(\`[data-goal-id="\${id}"]\`);
  if (goal) {
    goal.remove();
    updateGoalStats();
  }
}

function updateGoalStats() {
  const total = document.querySelectorAll('.goal-item').length;
  const completed = document.querySelectorAll('.goal-check:checked').length;
  document.getElementById('completed-goals').textContent = completed;
  document.getElementById('pending-goals').textContent = total - completed;
  document.getElementById('completion-rate').textContent = 
    total > 0 ? Math.round((completed / total) * 100) + '%' : '0%';
}

document.getElementById('goals-list').addEventListener('change', updateGoalStats);
<\/script>

<style>
.study-planner { max-width: 1100px; }
.planner-header { margin-bottom: 32px; }
.planner-header h3 { margin-bottom: 8px; }
.planner-header p { color: var(--text-secondary); }

.planner-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
  margin-bottom: 32px;
}

.goals-section,
.schedule-section {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 24px;
}

.goals-section h4,
.schedule-section h4 {
  margin-bottom: 20px;
  font-size: 16px;
}

.goals-list { margin-bottom: 20px; }
.goal-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  background: var(--bg-secondary);
  border-radius: var(--radius-md);
  margin-bottom: 8px;
}
.goal-check {
  width: 20px;
  height: 20px;
  accent-color: var(--accent);
}
.goal-content {
  flex: 1;
  display: flex;
  flex-direction: column;
}
.goal-text {
  font-size: 14px;
  color: var(--text-primary);
}
.goal-text.completed {
  text-decoration: line-through;
  color: var(--text-tertiary);
}
.goal-deadline {
  font-size: 12px;
  color: var(--text-tertiary);
}
.goal-delete {
  background: none;
  border: none;
  color: var(--text-tertiary);
  font-size: 20px;
  cursor: pointer;
  padding: 0 4px;
}
.goal-delete:hover {
  color: var(--danger);
}

.add-goal {
  display: flex;
  gap: 8px;
  margin-bottom: 20px;
}
.add-goal input[type="text"] {
  flex: 1;
  padding: 10px 14px;
  background: var(--bg-tertiary);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  color: var(--text-primary);
}
.add-goal input[type="date"] {
  padding: 10px 14px;
  background: var(--bg-tertiary);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  color: var(--text-primary);
}

.goal-stats {
  display: flex;
  gap: 24px;
  padding-top: 20px;
  border-top: 1px solid var(--border);
}
.stat-item {
  text-align: center;
}
.stat-number {
  display: block;
  font-size: 24px;
  font-weight: 700;
  color: var(--accent);
}
.stat-text {
  font-size: 12px;
  color: var(--text-tertiary);
}

.day-schedule {
  margin-bottom: 16px;
  padding-bottom: 16px;
  border-bottom: 1px solid var(--border);
}
.day-schedule:last-child {
  border-bottom: none;
  margin-bottom: 20px;
}
.day-header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
}
.day-name {
  font-weight: 600;
  font-size: 14px;
  color: var(--text-primary);
}
.day-date {
  font-size: 12px;
  color: var(--text-tertiary);
}
.study-slots { display: grid; gap: 6px; }
.study-slot {
  display: flex;
  flex-direction: column;
  padding: 10px 12px;
  background: var(--bg-secondary);
  border-radius: var(--radius-sm);
  border-left: 3px solid var(--accent);
}
.study-slot.completed {
  border-left-color: var(--success);
  opacity: 0.7;
}
.slot-time {
  font-size: 12px;
  color: var(--text-tertiary);
}
.slot-topic {
  font-size: 13px;
  color: var(--text-primary);
}

.focus-timer-section {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: var(--radius-lg);
  padding: 24px;
  text-align: center;
}
.focus-timer-section h4 {
  margin-bottom: 24px;
  font-size: 16px;
}

.timer-display {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
}
.timer-circle {
  position: relative;
  width: 200px;
  height: 200px;
}
.timer-circle svg {
  transform: rotate(-90deg);
  width: 100%;
  height: 100%;
}
.timer-text {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  display: flex;
  flex-direction: column;
  align-items: center;
}
#timer-countdown {
  font-size: 42px;
  font-weight: 700;
  color: var(--text-primary);
  line-height: 1;
}
.timer-label {
  font-size: 13px;
  color: var(--text-tertiary);
  margin-top: 4px;
}

.timer-controls {
  display: flex;
  gap: 12px;
}
.timer-btn {
  padding: 12px 24px;
  background: var(--accent);
  color: white;
  border: none;
  border-radius: var(--radius-md);
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}
.timer-btn:hover {
  background: var(--accent-hover);
  transform: translateY(-2px);
}
.timer-btn.secondary {
  background: var(--bg-tertiary);
  color: var(--text-primary);
}
.timer-btn.secondary:hover {
  background: var(--border);
}

.timer-presets {
  display: flex;
  gap: 8px;
  margin-top: 20px;
  flex-wrap: wrap;
  justify-content: center;
}
.preset-btn {
  padding: 8px 16px;
  background: var(--bg-tertiary);
  border: 1px solid var(--border);
  border-radius: 20px;
  color: var(--text-secondary);
  font-size: 13px;
  cursor: pointer;
  transition: all 0.2s;
}
.preset-btn:hover,
.preset-btn.active {
  background: var(--accent);
  border-color: var(--accent);
  color: white;
}

@media (max-width: 768px) {
  .planner-grid { grid-template-columns: 1fr; }
  .add-goal { flex-direction: column; }
  .timer-circle { width: 160px; height: 160px; }
  #timer-countdown { font-size: 32px; }
}
</style>`
        }
      ]
    }
  }
};

// Merge with KNOWLEDGE_BASE
if (typeof KNOWLEDGE_BASE !== 'undefined') {
  Object.assign(KNOWLEDGE_BASE, DASHBOARD_DATA);
}
