// Interactive Tools Data Module
const TOOLS_DATA = {
  tools: {
    title: "Tools",
    description: "Interactive tools for learning and practicing infrastructure concepts",
    color: "var(--info)",
    subtopics: {
      "Networking Tools": [
        {
          id: "subnet-calculator",
          title: "Interactive Subnet Calculator",
          tags: ["tool", "networking"],
          summary: "Calculate subnets, hosts, ranges, and visualize network breakdowns.",
          content: `<div class="tool-container">
    <h3>Subnet Calculator</h3>
    <div class="subnet-calculator">
        <div class="calc-input-group">
            <label>IP Address</label>
            <input type="text" id="calc-ip" placeholder="192.168.1.0" value="192.168.1.0">
        </div>
        <div class="calc-input-group">
            <label>CIDR Prefix</label>
            <select id="calc-cidr">
                <option value="24">/24 (255.255.255.0)</option>
                <option value="25">/25 (255.255.255.128)</option>
                <option value="26">/26 (255.255.255.192)</option>
                <option value="27">/27 (255.255.255.224)</option>
                <option value="28">/28 (255.255.255.240)</option>
                <option value="29">/29 (255.255.255.248)</option>
                <option value="30">/30 (255.255.255.252)</option>
                <option value="16">/16 (255.255.0.0)</option>
                <option value="8">/8 (255.0.0.0)</option>
            </select>
        </div>
        <button class="btn btn-primary" onclick="calculateSubnet()">Calculate</button>
    </div>
    
    <div id="calc-results" class="calc-results" style="display:none;">
        <div class="result-grid">
            <div class="result-item">
                <span class="result-label">Network Address</span>
                <span class="result-value" id="res-network">-</span>
            </div>
            <div class="result-item">
                <span class="result-label">Broadcast Address</span>
                <span class="result-value" id="res-broadcast">-</span>
            </div>
            <div class="result-item">
                <span class="result-label">Subnet Mask</span>
                <span class="result-value" id="res-mask">-</span>
            </div>
            <div class="result-item">
                <span class="result-label">Wildcard Mask</span>
                <span class="result-value" id="res-wildcard">-</span>
            </div>
            <div class="result-item">
                <span class="result-label">Total Hosts</span>
                <span class="result-value" id="res-total">-</span>
            </div>
            <div class="result-item">
                <span class="result-label">Usable Hosts</span>
                <span class="result-value" id="res-usable">-</span>
            </div>
            <div class="result-item">
                <span class="result-label">First Usable IP</span>
                <span class="result-value" id="res-first">-</span>
            </div>
            <div class="result-item">
                <span class="result-label">Last Usable IP</span>
                <span class="result-value" id="res-last">-</span>
            </div>
        </div>
        
        <div class="binary-breakdown">
            <h4>Binary Breakdown</h4>
            <div class="binary-visual" id="binary-visual">
                <!-- Generated by JS -->
            </div>
        </div>
    </div>
</div>

<script>
function calculateSubnet() {
    const ip = document.getElementById('calc-ip').value;
    const cidr = parseInt(document.getElementById('calc-cidr').value);
    
    if (!validateIP(ip)) {
        showToast('Invalid IP address', 'error');
        return;
    }
    
    const results = calculateSubnetDetails(ip, cidr);
    displayResults(results);
    document.getElementById('calc-results').style.display = 'block';
}

function validateIP(ip) {
    const parts = ip.split('.');
    if (parts.length !== 4) return false;
    return parts.every(part => {
        const num = parseInt(part);
        return num >= 0 && num <= 255;
    });
}

function calculateSubnetDetails(ip, cidr) {
    const parts = ip.split('.').map(Number);
    const ipLong = (parts[0] << 24) | (parts[1] << 16) | (parts[2] << 8) | parts[3];
    
    const mask = -1 << (32 - cidr);
    const networkLong = ipLong & mask;
    const broadcastLong = networkLong | (~mask >>> 0);
    
    const totalHosts = Math.pow(2, 32 - cidr);
    const usableHosts = totalHosts > 2 ? totalHosts - 2 : totalHosts;
    
    return {
        network: longToIP(networkLong),
        broadcast: longToIP(broadcastLong),
        mask: longToIP(mask >>> 0),
        wildcard: longToIP(~mask >>> 0),
        totalHosts: totalHosts,
        usableHosts: usableHosts,
        firstUsable: usableHosts > 0 ? longToIP(networkLong + 1) : '-',
        lastUsable: usableHosts > 0 ? longToIP(broadcastLong - 1) : '-',
        cidr: cidr
    };
}

function longToIP(long) {
    return [
        (long >>> 24) & 255,
        (long >>> 16) & 255,
        (long >>> 8) & 255,
        long & 255
    ].join('.');
}

function displayResults(results) {
    document.getElementById('res-network').textContent = results.network;
    document.getElementById('res-broadcast').textContent = results.broadcast;
    document.getElementById('res-mask').textContent = results.mask;
    document.getElementById('res-wildcard').textContent = results.wildcard;
    document.getElementById('res-total').textContent = results.totalHosts.toLocaleString();
    document.getElementById('res-usable').textContent = results.usableHosts.toLocaleString();
    document.getElementById('res-first').textContent = results.firstUsable;
    document.getElementById('res-last').textContent = results.lastUsable;
    
    // Binary visualization
    const networkParts = results.network.split('.');
    let binaryHtml = '';
    networkParts.forEach((part, idx) => {
        const binary = parseInt(part).toString(2).padStart(8, '0');
        const networkBits = Math.min(results.cidr - (idx * 8), 8);
        const hostBits = 8 - Math.max(networkBits, 0);
        
        let coloredBinary = '';
        if (networkBits > 0) {
            coloredBinary += '<span class="bit-network">' + binary.substring(0, networkBits) + '</span>';
        }
        if (hostBits > 0) {
            coloredBinary += '<span class="bit-host">' + binary.substring(networkBits) + '</span>';
        }
        
        binaryHtml += '<div class="binary-octet">' + coloredBinary + '</div>';
    });
    
    document.getElementById('binary-visual').innerHTML = binaryHtml;
}
</script>

<style>
.subnet-calculator {
    display: flex;
    gap: 16px;
    align-items: flex-end;
    margin-bottom: 24px;
    flex-wrap: wrap;
}
.calc-input-group {
    display: flex;
    flex-direction: column;
    gap: 8px;
}
.calc-input-group label {
    font-size: 13px;
    font-weight: 600;
    color: var(--text-secondary);
}
.calc-input-group input,
.calc-input-group select {
    padding: 10px 14px;
    background: var(--bg-input);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    color: var(--text-primary);
    font-size: 14px;
    min-width: 200px;
}
.calc-results {
    animation: fade-in-scale 0.3s ease;
}
.result-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 16px;
    margin-bottom: 24px;
}
.result-item {
    background: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    padding: 16px;
}
.result-label {
    display: block;
    font-size: 12px;
    color: var(--text-tertiary);
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-bottom: 4px;
}
.result-value {
    display: block;
    font-size: 18px;
    font-weight: 700;
    color: var(--accent);
    font-family: var(--font-mono);
}
.binary-breakdown {
    background: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    padding: 20px;
}
.binary-breakdown h4 {
    margin-bottom: 16px;
    font-size: 14px;
    font-weight: 600;
}
.binary-visual {
    display: flex;
    flex-direction: column;
    gap: 8px;
    font-family: var(--font-mono);
    font-size: 16px;
}
.binary-octet {
    letter-spacing: 2px;
}
.bit-network {
    color: var(--accent);
    font-weight: 600;
}
.bit-host {
    color: var(--success);
}
</style>`
        },
        {
          id: "linux-command-sim",
          title: "Linux Command Simulator",
          tags: ["tool", "linux"],
          summary: "Practice Linux commands in a simulated terminal environment.",
          content: `<div class="tool-container">
    <h3>Linux Command Simulator</h3>
    <div class="terminal-simulator">
        <div class="terminal-header">
            <div class="terminal-buttons">
                <span class="term-btn red"></span>
                <span class="term-btn yellow"></span>
                <span class="term-btn green"></span>
            </div>
            <span class="terminal-title">user@infrahub:~</span>
        </div>
        <div class="terminal-body" id="terminal-body">
            <div class="terminal-line">
                <span class="terminal-prompt">user@infrahub:~$</span>
                <span class="terminal-welcome">Welcome to InfraHub Linux Simulator! Type 'help' to get started.</span>
            </div>
        </div>
        <div class="terminal-input-line">
            <span class="terminal-prompt">user@infrahub:~$</span>
            <input type="text" id="terminal-input" placeholder="Type a command..." autocomplete="off">
        </div>
    </div>
    
    <div class="command-help">
        <h4>Available Commands</h4>
        <div class="command-list">
            <div class="command-item">
                <code>ls [options] [path]</code>
                <span>List directory contents</span>
            </div>
            <div class="command-item">
                <code>cd [directory]</code>
                <span>Change directory</span>
            </div>
            <div class="command-item">
                <code>pwd</code>
                <span>Print working directory</span>
            </div>
            <div class="command-item">
                <code>cat [file]</code>
                <span>Display file contents</span>
            </div>
            <div class="command-item">
                <code>mkdir [directory]</code>
                <span>Create directory</span>
            </div>
            <div class="command-item">
                <code>touch [file]</code>
                <span>Create empty file</span>
            </div>
            <div class="command-item">
                <code>rm [options] [file]</code>
                <span>Remove file/directory</span>
            </div>
            <div class="command-item">
                <code>cp [source] [dest]</code>
                <span>Copy files</span>
            </div>
            <div class="command-item">
                <code>mv [source] [dest]</code>
                <span>Move/rename files</span>
            </div>
            <div class="command-item">
                <code>help</code>
                <span>Show this help</span>
            </div>
            <div class="command-item">
                <code>clear</code>
                <span>Clear terminal</span>
            </div>
        </div>
    </div>
</div>

<script>
(function() {
    const terminalBody = document.getElementById('terminal-body');
    const terminalInput = document.getElementById('terminal-input');
    
    // Simulated file system
    let fileSystem = {
        '/': {
            type: 'dir',
            children: {
                'home': {
                    type: 'dir',
                    children: {
                        'user': {
                            type: 'dir',
                            children: {
                                'documents': {
                                    type: 'dir',
                                    children: {
                                        'notes.txt': { type: 'file', content: 'Welcome to InfraHub!\\nThis is a simulated file system.\\nPractice your Linux commands here.' },
                                        'script.sh': { type: 'file', content: '#!/bin/bash\\necho "Hello World"' }
                                    }
                                },
                                'projects': {
                                    type: 'dir',
                                    children: {
                                        'app': { type: 'dir', children: {} },
                                        'README.md': { type: 'file', content: '# My Projects\\n\\nThis directory contains my project files.' }
                                    }
                                },
                                '.bashrc': { type: 'file', content: '# Bash configuration' }
                            }
                        }
                    }
                },
                'etc': {
                    type: 'dir',
                    children: {
                        'hosts': { type: 'file', content: '127.0.0.1 localhost' },
                        'nginx': {
                            type: 'dir',
                            children: {
                                'nginx.conf': { type: 'file', content: 'server { listen 80; }' }
                            }
                        }
                    }
                },
                'var': {
                    type: 'dir',
                    children: {
                        'log': {
                            type: 'dir',
                            children: {
                                'syslog': { type: 'file', content: 'System logs...' }
                            }
                        }
                    }
                }
            }
        }
    };
    
    let currentPath = ['/home', 'user'];
    
    terminalInput.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') {
            const command = terminalInput.value.trim();
            if (command) {
                executeCommand(command);
                terminalInput.value = '';
            }
        }
    });
    
    function executeCommand(command) {
        const parts = command.split(' ');
        const cmd = parts[0];
        const args = parts.slice(1);
        
        // Add command to terminal
        addLine('user@infrahub:' + getPromptPath() + '$ ' + command, 'input');
        
        switch (cmd) {
            case 'ls':
                handleLs(args);
                break;
            case 'cd':
                handleCd(args);
                break;
            case 'pwd':
                addLine('/' + currentPath.join('/'));
                break;
            case 'cat':
                handleCat(args);
                break;
            case 'mkdir':
                handleMkdir(args);
                break;
            case 'touch':
                handleTouch(args);
                break;
            case 'rm':
                handleRm(args);
                break;
            case 'cp':
                handleCp(args);
                break;
            case 'mv':
                handleMv(args);
                break;
            case 'help':
                showHelp();
                break;
            case 'clear':
                terminalBody.innerHTML = '';
                break;
            default:
                addLine(cmd + ': command not found', 'error');
        }
        
        scrollToBottom();
    }
    
    function handleLs(args) {
        const node = getNodeAtPath(currentPath);
        if (!node || node.type !== 'dir') {
            addLine('ls: cannot access current directory', 'error');
            return;
        }
        
        const showAll = args.includes('-a');
        const longFormat = args.includes('-l');
        
        let entries = Object.keys(node.children || {});
        if (!showAll) {
            entries = entries.filter(e => !e.startsWith('.'));
        }
        
        if (longFormat) {
            entries.forEach(entry => {
                const child = node.children[entry];
                const type = child.type === 'dir' ? 'drwxr-xr-x' : '-rw-r--r--';
                const size = child.type === 'file' ? (child.content?.length || 0) : 4096;
                addLine(\`\${type} user user \${size.toString().padStart(8)} Jan 1 12:00 \${entry}\`);
            });
        } else {
            if (entries.length > 0) {
                addLine(entries.join('  '));
            }
        }
    }
    
    function handleCd(args) {
        const target = args[0] || '/home/user';
        const newPath = resolvePath(target);
        const node = getNodeAtPath(newPath);
        
        if (!node) {
            addLine('cd: ' + target + ': No such file or directory', 'error');
            return;
        }
        
        if (node.type !== 'dir') {
            addLine('cd: ' + target + ': Not a directory', 'error');
            return;
        }
        
        currentPath = newPath;
    }
    
    function handleCat(args) {
        if (args.length === 0) {
            addLine('cat: missing file operand', 'error');
            return;
        }
        
        const filePath = resolvePath(args[0]);
        const node = getNodeAtPath(filePath);
        
        if (!node) {
            addLine('cat: ' + args[0] + ': No such file or directory', 'error');
            return;
        }
        
        if (node.type === 'dir') {
            addLine('cat: ' + args[0] + ': Is a directory', 'error');
            return;
        }
        
        if (node.content) {
            node.content.split('\\n').forEach(line => addLine(line));
        }
    }
    
    function handleMkdir(args) {
        if (args.length === 0) {
            addLine('mkdir: missing operand', 'error');
            return;
        }
        
        const dirPath = resolvePath(args[0]);
        const parentPath = dirPath.slice(0, -1);
        const dirName = dirPath[dirPath.length - 1];
        const parent = getNodeAtPath(parentPath);
        
        if (!parent || parent.type !== 'dir') {
            addLine('mkdir: cannot create directory ' + args[0] + ': No such file or directory', 'error');
            return;
        }
        
        if (!parent.children) parent.children = {};
        parent.children[dirName] = { type: 'dir', children: {} };
        addLine('', 'success');
    }
    
    function handleTouch(args) {
        if (args.length === 0) {
            addLine('touch: missing file operand', 'error');
            return;
        }
        
        const filePath = resolvePath(args[0]);
        const parentPath = filePath.slice(0, -1);
        const fileName = filePath[filePath.length - 1];
        const parent = getNodeAtPath(parentPath);
        
        if (!parent || parent.type !== 'dir') {
            addLine('touch: cannot touch ' + args[0] + ': No such file or directory', 'error');
            return;
        }
        
        if (!parent.children) parent.children = {};
        if (!parent.children[fileName]) {
            parent.children[fileName] = { type: 'file', content: '' };
        }
    }
    
    function handleRm(args) {
        const recursive = args.includes('-r') || args.includes('-rf');
        const targets = args.filter(a => !a.startsWith('-'));
        
        if (targets.length === 0) {
            addLine('rm: missing operand', 'error');
            return;
        }
        
        targets.forEach(target => {
            const filePath = resolvePath(target);
            const parentPath = filePath.slice(0, -1);
            const fileName = filePath[filePath.length - 1];
            const parent = getNodeAtPath(parentPath);
            
            if (!parent || !parent.children || !parent.children[fileName]) {
                addLine('rm: cannot remove ' + target + ': No such file or directory', 'error');
                return;
            }
            
            const node = parent.children[fileName];
            if (node.type === 'dir' && !recursive) {
                addLine('rm: cannot remove ' + target + ': Is a directory', 'error');
                return;
            }
            
            delete parent.children[fileName];
        });
    }
    
    function handleCp(args) {
        if (args.length < 2) {
            addLine('cp: missing file operand', 'error');
            return;
        }
        // Simplified implementation
        addLine('cp: command simulation (simplified)');
    }
    
    function handleMv(args) {
        if (args.length < 2) {
            addLine('mv: missing file operand', 'error');
            return;
        }
        // Simplified implementation
        addLine('mv: command simulation (simplified)');
    }
    
    function getNodeAtPath(path) {
        let node = fileSystem['/'];
        for (const segment of path) {
            if (segment === '') continue;
            if (!node.children || !node.children[segment]) return null;
            node = node.children[segment];
        }
        return node;
    }
    
    function resolvePath(path) {
        if (path.startsWith('/')) {
            return path.split('/').filter(p => p);
        }
        
        const parts = [...currentPath];
        path.split('/').forEach(part => {
            if (part === '..') {
                parts.pop();
            } else if (part !== '.' && part !== '') {
                parts.push(part);
            }
        });
        return parts;
    }
    
    function getPromptPath() {
        return currentPath.length === 0 ? '/' : '/' + currentPath.join('/');
    }
    
    function addLine(text, type = 'output') {
        const line = document.createElement('div');
        line.className = 'terminal-line';
        if (type === 'error') line.classList.add('terminal-error');
        if (type === 'success') line.classList.add('terminal-success');
        line.textContent = text;
        terminalBody.appendChild(line);
    }
    
    function showHelp() {
        addLine('Available commands:');
        addLine('  ls [-a] [-l]     List directory contents');
        addLine('  cd [dir]         Change directory');
        addLine('  pwd              Print working directory');
        addLine('  cat [file]       Display file contents');
        addLine('  mkdir [dir]      Create directory');
        addLine('  touch [file]     Create empty file');
        addLine('  rm [-r] [file]   Remove file/directory');
        addLine('  cp [src] [dst]   Copy files');
        addLine('  mv [src] [dst]   Move/rename files');
        addLine('  help             Show this help');
        addLine('  clear            Clear terminal');
    }
    
    function scrollToBottom() {
        terminalBody.scrollTop = terminalBody.scrollHeight;
    }
    
    // Auto-focus input
    terminalInput.focus();
})();
</script>

<style>
.terminal-simulator {
    background: #0d1117;
    border-radius: var(--radius-lg);
    overflow: hidden;
    margin-bottom: 24px;
    box-shadow: var(--shadow-lg);
}
.terminal-header {
    background: #161b22;
    padding: 12px 16px;
    display: flex;
    align-items: center;
    gap: 12px;
    border-bottom: 1px solid #30363d;
}
.terminal-buttons {
    display: flex;
    gap: 8px;
}
.term-btn {
    width: 12px;
    height: 12px;
    border-radius: 50%;
}
.term-btn.red { background: #ff5f56; }
.term-btn.yellow { background: #ffbd2e; }
.term-btn.green { background: #27ca40; }
.terminal-title {
    flex: 1;
    text-align: center;
    font-size: 13px;
    color: var(--text-secondary);
    font-family: var(--font-mono);
}
.terminal-body {
    padding: 16px;
    min-height: 300px;
    max-height: 400px;
    overflow-y: auto;
    font-family: var(--font-mono);
    font-size: 14px;
    line-height: 1.6;
}
.terminal-line {
    margin-bottom: 4px;
    color: #e6edf3;
}
.terminal-line.terminal-error {
    color: #ff7b72;
}
.terminal-line.terminal-success {
    color: #7ee787;
}
.terminal-prompt {
    color: #7ee787;
    margin-right: 8px;
}
.terminal-input-line {
    display: flex;
    align-items: center;
    padding: 12px 16px;
    background: #0d1117;
    border-top: 1px solid #30363d;
}
.terminal-input-line input {
    flex: 1;
    background: transparent;
    border: none;
    color: #e6edf3;
    font-family: var(--font-mono);
    font-size: 14px;
    outline: none;
    margin-left: 8px;
}
.command-help {
    background: var(--bg-card);
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
    padding: 20px;
}
.command-help h4 {
    margin-bottom: 16px;
    font-size: 16px;
}
.command-list {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 12px;
}
.command-item {
    display: flex;
    align-items: center;
    gap: 12px;
}
.command-item code {
    background: var(--bg-secondary);
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 13px;
    font-family: var(--font-mono);
    color: var(--accent);
    min-width: 140px;
}
.command-item span {
    font-size: 13px;
    color: var(--text-secondary);
}
</style>`
        }
      ]
    }
  }
};

// Merge with main KNOWLEDGE_BASE
Object.assign(KNOWLEDGE_BASE, TOOLS_DATA);
